#
FROM ubuntu:18.10
WORKDIR /home/app
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y sudo
RUN apt-get install -y apt-utils
ENV TZ=America/Denver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN apt-get install -y tzdata
RUN echo "=== Done installing Ubuntu."
#
###
RUN apt-get install -y postgresql-10
RUN apt-cache policy postgresql-10
RUN apt-get install -y postgresql-server-dev-10
COPY conf/postgresql/pg_hba.conf /etc/postgresql/10/main/
RUN chmod 640 /etc/postgresql/10/main/pg_hba.conf 
RUN chown postgres /etc/postgresql/10/main/pg_hba.conf 
COPY conf/postgresql/postgresql.conf /etc/postgresql/10/main/
RUN chmod 644 /etc/postgresql/10/main/postgresql.conf
RUN chown postgres /etc/postgresql/10/main/postgresql.conf
RUN echo "=== Done installing PostgreSQL."
#
RUN mkdir -p /home/data/CARLSBAD
COPY data/carlsbad.pgdump /home/data/CARLSBAD
RUN echo "=== Done copying db data."
#
# Note that user postgres must start db differently than user root.
USER postgres
RUN pg_config
ENV dbname=carlsbad
ENV dbusr=batman
ENV dbpw=foobar
RUN /etc/init.d/postgresql start && \
	psql -c "CREATE ROLE ${dbusr} WITH LOGIN PASSWORD '${dbpw}'" && \
	createdb -O postgres ${dbname} && \
	pg_restore -v --schema public -d ${dbname} /home/data/CARLSBAD/carlsbad.pgdump && \
	psql -d ${dbname} -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${dbusr}" && \
	psql -d ${dbname} -c "GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${dbusr}" && \
	psql -d ${dbname} -c "GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ${dbusr}" && \
	psql -l
USER root
RUN service postgresql stop
RUN echo "=== Done instantiating and loading db."
#
# CMD must be in foreground.
CMD ["sudo", "-u", "postgres", "/usr/lib/postgresql/10/bin/postgres", "-D", "/var/lib/postgresql/10/main", "-c", "config_file=/etc/postgresql/10/main/postgresql.conf"]
#
