#
FROM ubuntu:18.10
WORKDIR /home/app
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update
RUN apt-get install -y apt-utils
ENV TZ=America/Denver
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ >/etc/timezone
RUN apt-get install -y tzdata
RUN echo "=== Done installing Ubuntu."
#
###
RUN apt-get install -y postgresql-10
RUN apt-cache policy postgresql-10
RUN apt-get install -y postgresql-server-dev-10
COPY conf/postgresql/pg_hba.conf /etc/postgresql/10/main/
RUN chmod 640 /etc/postgresql/10/main/pg_hba.conf 
RUN chown postgres /etc/postgresql/10/main/pg_hba.conf 
RUN echo "=== Done installing PostgreSQL."
#
RUN mkdir -p /home/data/carlsbad
COPY data/carlsbad.dump /home/data/carlsbad
RUN echo "=== Done copying db data."
#
USER postgres
RUN pg_config
RUN /etc/init.d/postgresql start && \
	psql -c "CREATE ROLE batman WITH LOGIN PASSWORD 'foobar'" && \
	createdb -O postgres carlsbad && \
	pg_restore --schema public -d carlsbad /home/data/carlsbad/carlsbad.dump && \
	psql -d carlsbad -c "GRANT SELECT ON ALL TABLES IN SCHEMA public TO batman" && \
	psql -d carlsbad -c "GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO batman" && \
	psql -d carlsbad -c "GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO batman" && \
	psql -l
RUN service postgresql stop
USER root
RUN echo "=== Done instantiating and loading db."
#
CMD ["/etc/init.d/postgresql", "start"]
#
